# test_config.yaml
stages:
  - name: smoke_tests
    steps:
      - name: gsm8k_small_g3_tp1
        flavor: g3
        command: >-
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1
      - name: gsm8k_small_g3_tp2
        flavor: g3.s
        command: >-
          
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 2
      - name: gsm8k_small_g2_tp1
        flavor: g2
        command: >-
          
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1
      - name: gsm8k_small_g2_tp2
        flavor: g2.s
        command: >-
          
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 2
  - name: full_test_suite
    steps:
      - name: gsm8k_small_g3_tp1_apc
        flavor: g3
        command: >-
          export VLLM_CONTIGUOUS_PA=false && 
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1 -a
      - name: gsm8k_small_g2_tp1_apc
        flavor: g2
        command: >-
          export VLLM_CONTIGUOUS_PA=false && 
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1 -a
      - name: gsm8k_medium_g3_tp1
        flavor: g3
        command: >-
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-medium.txt -t 1
      - name: gsm8k_medium_g3_tp2
        flavor: g3.s
        command: >-
          
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-medium.txt -t 2
      # Chendi: Failed on G2 due to Qwen3-30B might be too large
      # - name: gsm8k_medium_g2_tp1
      #   flavor: g2
      #   command: >-
      #     
      #     cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-medium.txt -t 1
      - name: gsm8k_medium_g2_tp2
        flavor: g2.s
        command: >-
          
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-medium.txt -t 2
      - name: gsm8k_large_g3_tp2
        flavor: g3.s
        command: >-
          
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-large.txt -t 2
      - name: gsm8k_large_g2_tp4
        flavor: g2.m
        command: >-
          
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-large.txt -t 4
      # Chendi: comment firstly since this one takes longest time and might fail on resource
      # - name: gsm8k_huge_g3_tp8
      #   flavor: g3.l
      #   command: >-
      #     
      #     cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-huge.txt -t 8
      - name: gsm8k_small_g3_tp1_fp8
        flavor: g3
        command: >-
          cd .jenkins/lm-eval-harness && 
          
          bash run-tests.sh -c configs/models-fp8-g3-tp1.txt -t 1
      - name: gsm8k_small_g3_tp2_fp8
        flavor: g3.s
        command: >-
          cd .jenkins/lm-eval-harness && 
          
          bash run-tests.sh -c configs/models-fp8.txt -t 2
      - name: gsm8k_fp8_llama4_scout_g3_tp2_compressed_tensor
        flavor: g3.s
        command: >-
          cd .jenkins/lm-eval-harness && 
          VLLM_WEIGHT_LOAD_FORCE_SYNC=1 VLLM_CONTIGUOUS_PA=False 
          bash run-tests.sh -c configs/models-fp8-compressedtensor.txt -t 2
      # Chendi: crash on model weight loading, need to fix
      # - name: gsm8k_fp8_qwen3_30B_g3_tp1_block_scale_dynamic
      #   flavor: g3
      #   command: >-
      #     cd .jenkins/lm-eval-harness && 
      #     VLLM_CONTIGUOUS_PA=False  
      #     bash run-tests.sh -c configs/models-fp8-blockfp8.txt -t 1
      # Chendi: crash on model weight loading, need to fix
      # - name: gsm8k_fp8_qwen3_30B_g3_tp1_block_scale_dequant
      #   flavor: g3
      #   command: >-
      #     cd .jenkins/lm-eval-harness && 
      #     VLLM_CONTIGUOUS_PA=False VLLM_HPU_FORCE_CHANNEL_FP8=0 
      #     bash run-tests.sh -c configs/models-fp8-blockfp8.txt -t 1
      - name: multimodal_llama4_scout_g3_tp2_ep
        flavor: g3.s
        command: >-
          cd .jenkins/vision && 
          VLLM_WEIGHT_LOAD_FORCE_SYNC=1 
          bash run-tests.sh -c configs/models-llama4-scout.txt -t 2
      - name: gsm8k_qwen35_g3_tp1
        flavor: g3
        command: >-
          # Qwen3.5 has dependency on newer transformers, which is not compatible with vllm's current version, 
          # so we need to temporarily upgrade it for this test and then restore the original version after the test.
          # Will be removed once vllm supports newer transformers
          export OLD_TRANSFORMERS_VER=$(pip show transformers | grep Version | awk '{print $2}') &&
          export OLD_HF_HUB_VER=$(pip show huggingface_hub | grep Version | awk '{print $2}') &&
          pip install transformers==5.3.0 huggingface_hub==1.7.1 --no-deps &&
          cd .jenkins/lm-eval-harness &&
          VLLM_FUSED_BLOCK_SOFTMAX_ADJUSTMENT=False VLLM_GRAPH_RESERVED_MEM=0.2
          bash run-tests.sh -c configs/models-qwen3.5.txt -t 1 ;
          pip install transformers==$OLD_TRANSFORMERS_VER huggingface_hub==$OLD_HF_HUB_VER --no-deps

